//addSbtPlugin("org.scala-js"         % "sbt-scalajs"              % "0.6.32")
addSbtPlugin("org.scala-js"         % "sbt-scalajs"              % "1.13.1")
//addSbtPlugin("org.portable-scala"   % "sbt-crossproject"         % "1.3.1")  // (1)
//addSbtPlugin("org.portable-scala"   % "sbt-scalajs-crossproject" % "1.3.1")    // (2)
//addSbtPlugin("org.scala-native"     % "sbt-scala-native"         % "0.4.14")  // (3)
//addSbtPlugin("org.tpolecat"         % "tut-plugin"               % "0.6.12")
//addSbtPlugin("com.artima.supersafe" % "sbtplugin"                % "1.1.5")
//addSbtPlugin("org.planet42"         % "laika-sbt"                % "0.11.0")
addSbtPlugin("org.scoverage"        % "sbt-scoverage"            % "2.0.8")
addSbtPlugin("org.scoverage"        % "sbt-coveralls"            % "1.3.1")
addSbtPlugin("org.scalameta"        % "sbt-scalafmt"             % "2.5.0")
addSbtPlugin("com.typesafe.sbt"     % "sbt-osgi"                 % "0.9.6")