//addSbtPlugin("org.scala-js"         % "sbt-scalajs"              % "0.6.32")
addSbtPlugin("org.scala-js"         % "sbt-scalajs"              % "1.0.0")
addSbtPlugin("org.portable-scala"   % "sbt-crossproject"         % "1.0.0")  // (1)
addSbtPlugin("org.portable-scala"   % "sbt-scalajs-crossproject" % "1.0.0")    // (2)
addSbtPlugin("org.scala-native"     % "sbt-scala-native"         % "0.3.7")  // (3)
addSbtPlugin("org.tpolecat"         % "tut-plugin"               % "0.6.13")
//addSbtPlugin("com.artima.supersafe" % "sbtplugin"                % "1.1.5")
addSbtPlugin("org.planet42"         % "laika-sbt"                % "0.11.0")
addSbtPlugin("org.scoverage"        % "sbt-scoverage"            % "1.6.0")
addSbtPlugin("org.scoverage"        % "sbt-coveralls"            % "1.2.7")
addSbtPlugin("org.scalameta"        % "sbt-scalafmt"             % "2.0.0")
addSbtPlugin("com.typesafe.sbt"     % "sbt-osgi"                 % "0.9.5")