addSbtPlugin("org.scala-js"         % "sbt-scalajs"              % "0.6.23")
addSbtPlugin("org.portable-scala"   % "sbt-crossproject"         % "0.4.0")  // (1)
addSbtPlugin("org.portable-scala"   % "sbt-scalajs-crossproject" % "0.4.0")  // (2)
addSbtPlugin("org.scala-native"     % "sbt-scala-native"         % "0.3.7")  // (3)
addSbtPlugin("org.tpolecat"         % "tut-plugin"               % "0.6.3")
//addSbtPlugin("com.artima.supersafe" % "sbtplugin"                % "1.1.5")
addSbtPlugin("org.planet42"         % "laika-sbt"                % "0.7.5")
addSbtPlugin("org.scoverage"        % "sbt-scoverage"            % "1.5.1")
addSbtPlugin("org.scoverage"        % "sbt-coveralls"            % "1.2.4")
addSbtPlugin("com.geirsson"         % "sbt-scalafmt"             % "1.4.0")
addSbtPlugin("com.typesafe.sbt"     % "sbt-osgi"                 % "0.9.3")